POST http://localhost:5000/doctor/adddoctor
Content-Type: application/json
{   "name": "Dr. Ramesh",
    "specialization": "Pediatrician",
    "location": "Kerala, India",
    "qualification": "MBBS,MD",
    "hospital": "City Hospital",
    "year": 4,
    "fee": 250
}


 